function [trainedModel, validationRMSE,validationPredictions] = trainRegressionModel12(trainingData)
% [trainedModel, validationRMSE] = trainRegressionModel(trainingData)
% returns a trained regression model and its RMSE. This code recreates the
% model trained in Regression Learner app. Use the generated code to
% automate training the same model with new data, or to learn how to
% programmatically train models.
%
%  Input:
%      trainingData: a matrix with the same number of columns and data type
%       as imported into the app.
%
%  Output:
%      trainedModel: a struct containing the trained regression model. The
%       struct contains various fields with information about the trained
%       model.
%
%      trainedModel.predictFcn: a function to make predictions on new data.
%
%      validationRMSE: a double containing the RMSE. In the app, the
%       History list displays the RMSE for each model.
%
% Use the code to train the model with new data. To retrain your model,
% call the function from the command line with your original data or new
% data as the input argument trainingData.
%
% For example, to retrain a regression model trained with the original data
% set T, enter:
%   [trainedModel, validationRMSE] = trainRegressionModel(T)
%
% To make predictions with the returned 'trainedModel' on new data T2, use
%   yfit = trainedModel.predictFcn(T2)
%
% T2 must be a matrix containing only the predictor columns used for
% training. For details, enter:
%   trainedModel.HowToPredict

% Auto-generated by MATLAB on 29-Jan-2019 17:19:34

%%
% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
% Convert input to table
%
commandline = ['inputTable = array2table(trainingData, ''VariableNames'', {'];
for i = 1:size(trainingData,2)
    commandline = [commandline, '''column_', num2str(i), ''', '];
    if i == size(trainingData,2)
        commandline = [commandline, '});'];
    end
end
eval(commandline)
%
commandline = ['predictorNames = {'];
for i = 1:size(trainingData,2)-1
    commandline = [commandline, '''column_', num2str(i), ''', '];
    if i == size(trainingData,2)-1
        commandline = [commandline, '};'];
    end
end
eval(commandline)
%
predictors = inputTable(:, predictorNames);
%
commandline = ['response = inputTable.column_', num2str(size(trainingData,2)), ';'];
eval(commandline)
%
commandline = ['isCategoricalPredictor = ['];
for i = 1:size(trainingData,2)-1
    commandline = [commandline, 'false, '];
    if i == size(trainingData,2)-1
        commandline = [commandline, '];'];
    end
end
eval(commandline)

%%
%
% if size(trainingData,2)==14
%     inputTable = array2table(trainingData, 'VariableNames', {'column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6', 'column_7', 'column_8', 'column_9', 'column_10', 'column_11', 'column_12', 'column_13', 'column_14'});
% elseif size(trainingData,2)==13
%     inputTable = array2table(trainingData, 'VariableNames', {'column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6', 'column_7', 'column_8', 'column_9', 'column_10', 'column_11', 'column_12', 'column_13'});
% elseif size(trainingData,2)==6
%     inputTable = array2table(trainingData, 'VariableNames', {'column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6'});
% end
% if size(trainingData,2)==14
%     predictorNames = {'column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6', 'column_7', 'column_8', 'column_9', 'column_10', 'column_11', 'column_12', 'column_13'};
% elseif size(trainingData,2)==13
%     predictorNames = {'column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6', 'column_7', 'column_8', 'column_9', 'column_10', 'column_11', 'column_12'};
% elseif size(trainingData,2)==6
%     predictorNames = {'column_1', 'column_2', 'column_3', 'column_4', 'column_5'};
% end
% predictors = inputTable(:, predictorNames);
% if size(trainingData,2)==14
%     response = inputTable.column_14;
% elseif size(trainingData,2)==13
%     response = inputTable.column_13;
% elseif size(trainingData,2)==6
%     response = inputTable.column_6;
% end
% if size(trainingData,2)==14
%     isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false];
% elseif size(trainingData,2)==13
%     isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false];
% elseif size(trainingData,2)==6
%     isCategoricalPredictor = [false, false, false, false, false];
% end

% Train a regression model
% This code specifies all the model options and trains the model.
responseScale = iqr(response);
if ~isfinite(responseScale) || responseScale == 0.0
    responseScale = 1.0;
end
boxConstraint = responseScale/1.349;
epsilon = responseScale/13.49;
regressionSVM = fitrsvm(...
    predictors, ...
    response, ...
    'KernelFunction', 'polynomial', ...
    'PolynomialOrder', 3, ...
    'KernelScale', 'auto', ...
    'BoxConstraint', boxConstraint, ...
    'Epsilon', epsilon, ...
    'Standardize', true);
% regressionSVM = fitrsvm(...
%     predictors, ...
%     response, ...
%     'KernelFunction', 'gaussian', ...
%     'KernelScale', 'auto', ...
%     'BoxConstraint', boxConstraint, ...
%     'Epsilon', epsilon, ...
%     'Standardize', true);


% regressionSVM = fitrsvm(...
%     predictors, ...
%     response, ...
%     'KernelFunction', 'linear', ...
%     'KernelScale', 'auto', ...
%     'BoxConstraint', boxConstraint, ...
%     'Epsilon', epsilon, ...
%     'Standardize', true);


% Create the result struct with predict function
predictorExtractionFcn = @(x) array2table(x, 'VariableNames', predictorNames);
svmPredictFcn = @(x) predict(regressionSVM, x);
trainedModel.predictFcn = @(x) svmPredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedModel.RegressionSVM = regressionSVM;
trainedModel.About = 'This struct is a trained model exported from Regression Learner R2018a.';
trainedModel.HowToPredict = sprintf('To make predictions on a new predictor column matrix, X, use: \n  yfit = c.predictFcn(X) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nX must contain exactly 13 columns because this model was trained using 13 predictors. \nX must contain only predictor columns in exactly the same order and format as your training \ndata. Do not include the response column or any columns you did not import into the app. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appregression_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
% Convert input to table
% if size(trainingData,2)==14
%     inputTable = array2table(trainingData, 'VariableNames', {'column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6', 'column_7', 'column_8', 'column_9', 'column_10', 'column_11', 'column_12', 'column_13', 'column_14'});
% elseif size(trainingData,2)==13
%     inputTable = array2table(trainingData, 'VariableNames', {'column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6', 'column_7', 'column_8', 'column_9', 'column_10', 'column_11', 'column_12', 'column_13'});
% elseif size(trainingData,2)==6
%     inputTable = array2table(trainingData, 'VariableNames', {'column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6'});
% end
%
% %
% if size(trainingData,2)==14
%     predictorNames = {'column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6', 'column_7', 'column_8', 'column_9', 'column_10', 'column_11', 'column_12', 'column_13'};
% elseif size(trainingData,2)==13
%     predictorNames = {'column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6', 'column_7', 'column_8', 'column_9', 'column_10', 'column_11', 'column_12'};
% elseif size(trainingData,2)==6
%     predictorNames = {'column_1', 'column_2', 'column_3', 'column_4', 'column_5'};
% end
% predictors = inputTable(:, predictorNames);
% if size(trainingData,2)==14
%     response = inputTable.column_14;
% elseif size(trainingData,2)==13
%     response = inputTable.column_13;
% elseif size(trainingData,2)==6
%     response = inputTable.column_6;
% end
% if size(trainingData,2)==14
%     isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false];
% elseif size(trainingData,2)==13
%     isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false];
% elseif size(trainingData,2)==6
%     isCategoricalPredictor = [false, false, false, false, false];
% end

% Perform cross-validation
KFolds = 5;
cvp = cvpartition(size(response, 1), 'KFold', KFolds);
% Initialize the predictions to the proper sizes
validationPredictions = response;
for fold = 1:KFolds
    trainingPredictors = predictors(cvp.training(fold), :);
    trainingResponse = response(cvp.training(fold), :);
    foldIsCategoricalPredictor = isCategoricalPredictor;
    
    % Train a regression model
    % This code specifies all the model options and trains the model.
    responseScale = iqr(trainingResponse);
    if ~isfinite(responseScale) || responseScale == 0.0
        responseScale = 1.0;
    end
    boxConstraint = responseScale/1.349;
    epsilon = responseScale/13.49;
    regressionSVM = fitrsvm(...
        trainingPredictors, ...
        trainingResponse, ...
        'KernelFunction', 'polynomial', ...
        'PolynomialOrder', 3, ...
        'KernelScale', 'auto', ...
        'BoxConstraint', boxConstraint, ...
        'Epsilon', epsilon, ...
        'Standardize', true);
    
    % Create the result struct with predict function
    svmPredictFcn = @(x) predict(regressionSVM, x);
    validationPredictFcn = @(x) svmPredictFcn(x);
    
    % Add additional fields to the result struct
    
    % Compute validation predictions
    validationPredictors = predictors(cvp.test(fold), :);
    foldPredictions = validationPredictFcn(validationPredictors);
    
    % Store predictions in the original order
    validationPredictions(cvp.test(fold), :) = foldPredictions;
end

% Compute validation RMSE
isNotMissing = ~isnan(validationPredictions) & ~isnan(response);
validationRMSE = sqrt(nansum(( validationPredictions - response ).^2) / numel(response(isNotMissing) ));
%[~,~,~,~,stats] = regress(validationPredictions,response);stats(1);